NORLOOK_TOOLCHAIN_LABEL = $(call qstrip,$(BR2_NORLOOK_TOOLCHAIN_LABEL))
NORLOOK_TOOLCHAIN_LIBC  = $(call qstrip,$(BR2_TOOLCHAIN_BUILDROOT_LIBC))

include $(BR2_EXTERNAL_NORLOOK_PATH)/package/package.mk
